import type { JsonRpcRequest } from "@components-kit/open-workbook-protocol";
import {
  appendTableRows,
  applyTableFilters,
  calculateWorkbook,
  captureSheetFingerprint,
  captureStyleFingerprint,
  captureTemplate,
  clearTableDataKeepFormulas,
  clearTableFilters,
  clearTableSort,
  closeWorkbook,
  convertFormulasToValues,
  copyChartFromTemplate,
  copyFormulaPatterns,
  copyPivotTableFromTemplate,
  copyStyleDimensions,
  copyTableStructure,
  createChart,
  createName,
  createPivotTable,
  createTable,
  deleteChart,
  deleteName,
  deletePivotTable,
  embedWorkbookLocalConfig,
  executeBatch,
  exportWorkbookFile,
  fillFormulaPattern,
  findBlankCells,
  findFormulaErrors,
  getActiveWorkbookContext,
  getChartInfo,
  getName,
  getPivotTableInfo,
  getRuntimeCapabilities,
  getSelection,
  getTableInfo,
  getWorkbookInfo,
  getWorkbookMap,
  listCharts,
  listNames,
  listPivotTables,
  listTables,
  readFormulaPatterns,
  readRangeComments,
  readRangeConditionalFormatting,
  readRangeDataValidation,
  readRangeHyperlinks,
  readRangeMergedCells,
  readRangeNotes,
  readTable,
  readWorkbookEmbeddedLocalConfig,
  refreshAllPivotTables,
  refreshChart,
  refreshPivotTable,
  reorderTableColumns,
  repairTemplateConsistency,
  resizeTable,
  saveWorkbook,
  searchRange,
  setActiveSheet,
  setTableStyle,
  setTableTotalRow,
  snapshotRanges,
  sortTable,
  updateChartDataSource,
  updateName,
  updateTableRows
} from "./excel-executor.js";

type RpcHandler = (params: unknown) => Promise<unknown> | unknown;

const handlers: Record<string, RpcHandler> = {
  "runtime.ping": (params) => ({ ok: true, at: new Date().toISOString(), echo: params }),
  "runtime.get_active_context": () => getActiveWorkbookContext(),
  "runtime.get_selection": () => getSelection(),
  "runtime.set_active_sheet": (params) => setActiveSheet((params as { sheetName: string }).sheetName),
  "workbook.get_info": () => getWorkbookInfo(),
  "workbook.get_map": () => getWorkbookMap(),
  "workbook.calculate": (params) => calculateWorkbook((params as { calculationType?: "full" | "recalculate" }).calculationType),
  "workbook.save": () => saveWorkbook(),
  "workbook.get_file": (params) => exportWorkbookFile((params as { workbookId: string; sliceSize?: number }).workbookId, (params as { sliceSize?: number }).sliceSize),
  "workbook.close": (params) => closeWorkbook((params as { closeBehavior?: "Save" | "SkipSave" }).closeBehavior),
  "workbook.snapshot_ranges": (params) => snapshotRanges((params as { workbookId: string }).workbookId, (params as { ranges: Parameters<typeof snapshotRanges>[1] }).ranges),
  "workbook.embed_local_config": (params) => embedWorkbookLocalConfig(params as Parameters<typeof embedWorkbookLocalConfig>[0]),
  "workbook.read_embedded_local_config": (params) => readWorkbookEmbeddedLocalConfig((params as { workbookId: string }).workbookId),
  "names.list": (params) => listNames((params as { workbookId: string }).workbookId),
  "names.get": (params) => getName(params as Parameters<typeof getName>[0]),
  "names.create": (params) => createName(params as Parameters<typeof createName>[0]),
  "names.update": (params) => updateName(params as Parameters<typeof updateName>[0]),
  "names.delete": (params) => deleteName(params as Parameters<typeof deleteName>[0]),
  "pivot.list": (params) => listPivotTables((params as { workbookId: string }).workbookId),
  "pivot.get_info": (params) => getPivotTableInfo(params as Parameters<typeof getPivotTableInfo>[0]),
  "pivot.create": (params) => createPivotTable(params as Parameters<typeof createPivotTable>[0]),
  "pivot.refresh": (params) => refreshPivotTable(params as Parameters<typeof refreshPivotTable>[0]),
  "pivot.refresh_all": (params) => refreshAllPivotTables((params as { workbookId: string }).workbookId),
  "pivot.copy_from_template": (params) => copyPivotTableFromTemplate(params as Parameters<typeof copyPivotTableFromTemplate>[0]),
  "pivot.delete": (params) => deletePivotTable(params as Parameters<typeof deletePivotTable>[0]),
  "chart.list": (params) => listCharts((params as { workbookId: string }).workbookId),
  "chart.get_info": (params) => getChartInfo(params as Parameters<typeof getChartInfo>[0]),
  "chart.create": (params) => createChart(params as Parameters<typeof createChart>[0]),
  "chart.update_data_source": (params) => updateChartDataSource(params as Parameters<typeof updateChartDataSource>[0]),
  "chart.copy_from_template": (params) => copyChartFromTemplate(params as Parameters<typeof copyChartFromTemplate>[0]),
  "chart.refresh": (params) => refreshChart(params as Parameters<typeof refreshChart>[0]),
  "chart.delete": (params) => deleteChart(params as Parameters<typeof deleteChart>[0]),
  "range.read_hyperlinks": (params) => readRangeHyperlinks(params as Parameters<typeof readRangeHyperlinks>[0]),
  "range.read_comments": (params) => readRangeComments(params as Parameters<typeof readRangeComments>[0]),
  "range.read_notes": (params) => readRangeNotes(params as Parameters<typeof readRangeNotes>[0]),
  "range.read_merged_cells": (params) => readRangeMergedCells(params as Parameters<typeof readRangeMergedCells>[0]),
  "range.read_data_validation": (params) => readRangeDataValidation(params as Parameters<typeof readRangeDataValidation>[0]),
  "range.read_conditional_formatting": (params) => readRangeConditionalFormatting(params as Parameters<typeof readRangeConditionalFormatting>[0]),
  "range.search": (params) => searchRange(params as Parameters<typeof searchRange>[0]),
  "range.find_blank_cells": (params) => findBlankCells(params as Parameters<typeof findBlankCells>[0]),
  "range.find_errors": (params) => findFormulaErrors(params as Parameters<typeof findFormulaErrors>[0]),
  "formula.read_patterns": (params) => readFormulaPatterns(params as Parameters<typeof readFormulaPatterns>[0]),
  "formula.copy_patterns": (params) => copyFormulaPatterns(params as Parameters<typeof copyFormulaPatterns>[0]),
  "formula.fill_pattern": (params) => fillFormulaPattern(params as Parameters<typeof fillFormulaPattern>[0]),
  "formula.convert_to_values": (params) => convertFormulasToValues(params as Parameters<typeof convertFormulasToValues>[0]),
  "table.list": (params) => listTables((params as { workbookId: string }).workbookId),
  "table.get_info": (params) => getTableInfo(params as Parameters<typeof getTableInfo>[0]),
  "table.read": (params) => readTable(params as Parameters<typeof readTable>[0]),
  "table.create": (params) => createTable(params as Parameters<typeof createTable>[0]),
  "table.resize": (params) => resizeTable(params as Parameters<typeof resizeTable>[0]),
  "table.reorder_columns": (params) => reorderTableColumns(params as Parameters<typeof reorderTableColumns>[0]),
  "table.append_rows": (params) => appendTableRows(params as Parameters<typeof appendTableRows>[0]),
  "table.update_rows": (params) => updateTableRows(params as Parameters<typeof updateTableRows>[0]),
  "table.clear_data_keep_formulas": (params) => clearTableDataKeepFormulas(params as Parameters<typeof clearTableDataKeepFormulas>[0]),
  "table.clear_filters": (params) => clearTableFilters(params as Parameters<typeof clearTableFilters>[0]),
  "table.apply_filters": (params) => applyTableFilters(params as Parameters<typeof applyTableFilters>[0]),
  "table.sort": (params) => sortTable(params as Parameters<typeof sortTable>[0]),
  "table.clear_sort": (params) => clearTableSort(params as Parameters<typeof clearTableSort>[0]),
  "table.set_total_row": (params) => setTableTotalRow(params as Parameters<typeof setTableTotalRow>[0]),
  "table.set_style": (params) => setTableStyle(params as Parameters<typeof setTableStyle>[0]),
  "table.copy_structure": (params) => copyTableStructure(params as Parameters<typeof copyTableStructure>[0]),
  "operation.execute_batch": (params) => executeBatch(params as Parameters<typeof executeBatch>[0]),
  "template.capture": (params) => captureTemplate(params as Parameters<typeof captureTemplate>[0]),
  "template.capture_sheet": (params) => captureSheetFingerprint(params as Parameters<typeof captureSheetFingerprint>[0]),
  "style.capture_fingerprint": (params) => captureStyleFingerprint(params as Parameters<typeof captureStyleFingerprint>[0]),
  "style.copy_dimensions": (params) => copyStyleDimensions(params as Parameters<typeof copyStyleDimensions>[0]),
  "template.repair": (params) => repairTemplateConsistency(params as Parameters<typeof repairTemplateConsistency>[0])
};

export function getRuntimeHelloPayload() {
  return {
    host: "excel",
    runtime: "office-js",
    capabilities: getRuntimeCapabilities()
  };
}

export async function handleAddinRpcRequest(request: JsonRpcRequest): Promise<{ ok: true; result: unknown } | { ok: false; message: string }> {
  if (request.method === "runtime.disconnect") {
    return { ok: true, result: { ok: true } };
  }
  const handler = handlers[request.method];
  if (!handler) {
    return { ok: false, message: `Method not implemented in add-in: ${request.method}` };
  }
  return { ok: true, result: await handler(request.params) };
}
