import type { ExcelCapabilityGroupDefinition } from "../types.js";

const registryContractTest = "apps/backend/src/capabilities/registry.test.ts";

export const BACKEND_CAPABILITY_DOMAINS: ExcelCapabilityGroupDefinition[] = [
  { group: "agent", label: "Agent", description: "Public agent entrypoint and agent-run control surface.", prefixes: ["excel.agent."], implementationOwner: "AgentOrchestrator", unitTestFile: registryContractTest },
  { group: "runtime", label: "Runtime", description: "Backend/add-in runtime discovery, session, and active context operations.", prefixes: ["excel.runtime."], implementationOwner: "RuntimeCapabilityDomain", unitTestFile: registryContractTest },
  { group: "workbook", label: "Workbook", description: "Workbook-level metadata, persistence, calculation, export, and local config operations.", prefixes: ["excel.workbook."], implementationOwner: "WorkbookCapabilityDomain", unitTestFile: registryContractTest },
  { group: "backup", label: "Backup", description: "Local workbook backup lifecycle, retention, pinning, verification, and restore operations.", prefixes: ["excel.backup."], implementationOwner: "BackupCapabilityDomain", unitTestFile: registryContractTest },
  { group: "worksheet", label: "Worksheet", description: "Worksheet metadata and structural sheet operations.", prefixes: ["excel.sheet."], implementationOwner: "WorksheetCapabilityDomain", unitTestFile: registryContractTest },
  { group: "range", label: "Range", description: "Cell range reads, writes, formatting, movement, and shape operations.", prefixes: ["excel.range."], implementationOwner: "RangeCapabilityDomain", unitTestFile: registryContractTest },
  { group: "lookup", label: "Lookup", description: "Workbook search, target resolution, header discovery, and candidate inspection operations.", prefixes: ["excel.lookup."], implementationOwner: "LookupCapabilityDomain", unitTestFile: registryContractTest },
  { group: "batch", label: "Batch", description: "Compiled operation preflight, validation, dry-run, submit, and apply operations.", prefixes: ["excel.batch."], implementationOwner: "BatchPlanCapabilityDomain", unitTestFile: registryContractTest },
  { group: "workflow", label: "Workflow", description: "Combined workbook workflows that compose multiple internal capabilities.", prefixes: ["excel.workflow."], implementationOwner: "AgentOrchestrator", unitTestFile: registryContractTest },
  { group: "plan", label: "Plan", description: "Plan preview, rebase, apply, and rollback operations.", prefixes: ["excel.plan."], implementationOwner: "BatchPlanCapabilityDomain", unitTestFile: registryContractTest },
  { group: "job", label: "Job", description: "Queued job list, status, wait, and cancellation operations.", prefixes: ["excel.job."], implementationOwner: "BatchPlanCapabilityDomain", unitTestFile: registryContractTest },
  { group: "task", label: "Task", description: "Collaborative task claim, progress, blocker, schedule, completion, and failure operations.", prefixes: ["excel.task."], implementationOwner: "CollaborationCapabilityDomain", unitTestFile: registryContractTest },
  { group: "collaboration", label: "Collaboration", description: "Agent, task, lock, transaction, conflict, and event collaboration views.", prefixes: ["excel.collab."], implementationOwner: "CollaborationCapabilityDomain", unitTestFile: registryContractTest },
  { group: "lock", label: "Lock", description: "Manual and policy-driven workbook lock operations.", prefixes: ["excel.lock."], implementationOwner: "CollaborationCapabilityDomain", unitTestFile: registryContractTest },
  { group: "conflict", label: "Conflict", description: "Conflict guidance, explanation, and telemetry operations.", prefixes: ["excel.conflict."], implementationOwner: "CollaborationCapabilityDomain", unitTestFile: registryContractTest },
  { group: "transaction", label: "Transaction", description: "Transaction status, wait, cancellation, rollback preview, and rollback operations.", prefixes: ["excel.transaction."], implementationOwner: "BatchPlanCapabilityDomain", unitTestFile: registryContractTest },
  { group: "events", label: "Events", description: "Runtime event subscription, recent-event, clear, and debounce operations.", prefixes: ["excel.events."], implementationOwner: "RuntimeCapabilityDomain", unitTestFile: registryContractTest },
  { group: "snapshot", label: "Snapshot", description: "Workbook snapshot creation, refresh, comparison, invalidation, list, and delete operations.", prefixes: ["excel.snapshot."], implementationOwner: "SnapshotCapabilityDomain", unitTestFile: registryContractTest },
  { group: "template", label: "Template", description: "Template detection, registration, region inference, fill, validation, and repair operations.", prefixes: ["excel.template."], implementationOwner: "TemplateCapabilityDomain", unitTestFile: registryContractTest },
  { group: "formatting", label: "Formatting", description: "Style fingerprints, themes, template style copy, consistency, and formatting repair operations.", prefixes: ["excel.style."], implementationOwner: "StyleCapabilityDomain", unitTestFile: registryContractTest },
  { group: "formula", label: "Formula", description: "Formula pattern, validation, repair, dependency, trace, recalculation, and explanation operations.", prefixes: ["excel.formula."], implementationOwner: "FormulaCapabilityDomain", unitTestFile: registryContractTest },
  { group: "table", label: "Table", description: "Excel table schema, compact read, structure, row, filter, sort, total-row, and style operations.", prefixes: ["excel.table."], implementationOwner: "TableCapabilityDomain", unitTestFile: registryContractTest },
  { group: "pivot", label: "PivotTables", description: "PivotTable creation, refresh, source, template copy, validation, fingerprint, diff, repair, and rebuild operations.", prefixes: ["excel.pivot."], implementationOwner: "PivotCapabilityDomain", unitTestFile: registryContractTest },
  { group: "chart", label: "Charts", description: "Chart list, metadata, create, source update, template copy, refresh, delete, and validation operations.", prefixes: ["excel.chart."], implementationOwner: "ChartCapabilityDomain", unitTestFile: registryContractTest },
  { group: "names", label: "Names", description: "Named range list, get, create, update, and delete operations.", prefixes: ["excel.names."], implementationOwner: "NamesCapabilityDomain", unitTestFile: registryContractTest },
  { group: "region", label: "Regions", description: "Detected and registered region list, get, clear, write, and fill operations.", prefixes: ["excel.region."], implementationOwner: "RegionCapabilityDomain", unitTestFile: registryContractTest },
  { group: "validation", label: "Validation", description: "Workbook, sheet, template, formula, style, table, filter, layout, reference, error, and unintended-change validation.", prefixes: ["excel.validate."], implementationOwner: "ValidationCapabilityDomain", unitTestFile: registryContractTest },
  { group: "repair", label: "Repair", description: "Template-backed style, formula, filter, table, print layout, named range, formula error, and merged-cell repair operations.", prefixes: ["excel.repair."], implementationOwner: "RepairCapabilityDomain", unitTestFile: registryContractTest },
  { group: "cleaning", label: "Cleaning", description: "Header, whitespace, duplicate, date, number, currency, missing value, split, merge, outlier, and fuzzy-match cleanup operations.", prefixes: ["excel.clean."], implementationOwner: "CleaningCapabilityDomain", unitTestFile: registryContractTest },
  { group: "permissions", label: "Permissions", description: "Permission, confirmation, scope, destructive-action, macro, and region lock policy operations.", prefixes: ["excel.permissions."], implementationOwner: "PermissionsCapabilityDomain", unitTestFile: registryContractTest }
];
